"""initial schema

Revision ID: ad202c056943
Revises: 
Create Date: 2025-12-27 20:43:56.564798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad202c056943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.String(length=255), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzle_runs_created_at'), 'puzzle_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_puzzle_runs_puzzle_id'), 'puzzle_runs', ['puzzle_id'], unique=False)
    op.create_table('execution_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('execution_simulation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage_flow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dag_structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['puzzle_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('physical_plan', sa.Text(), nullable=True),
    sa.Column('logical_plan', sa.Text(), nullable=True),
    sa.Column('spark_ui_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['puzzle_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('time_simulated', sa.Float(), nullable=True),
    sa.Column('shuffles', sa.Integer(), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=True),
    sa.Column('skew_detected', sa.Boolean(), nullable=True),
    sa.Column('cache_used', sa.Boolean(), nullable=True),
    sa.Column('broadcast_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['puzzle_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('output_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['puzzle_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_outputs')
    op.drop_table('run_metrics')
    op.drop_table('execution_plans')
    op.drop_table('execution_data')
    op.drop_index(op.f('ix_puzzle_runs_puzzle_id'), table_name='puzzle_runs')
    op.drop_index(op.f('ix_puzzle_runs_created_at'), table_name='puzzle_runs')
    op.drop_table('puzzle_runs')
    # ### end Alembic commands ###
